### PR TITLE
Solution to #1

### PR DESCRIPTION
**Pull request by ShellAddicted**
Solution for #1 
`adapt_confluence_page()` needs to be tested.
I'm waiting for a confluence test page.

### CODE REVIEW

**Comment by ShellAddicted** [comment]
can you review https://github.com/dialogs/dialog-office-bot/commit/7eb1f61393b376fca150db55ad47a00e30910970 ?
it works, let me know if you need some tweaks.

**Comment by Drymonade** [comment]
@ShellAddicted ok, will review soon.

**Comment by ShellAddicted** [comment]
@Drymonade with https://github.com/dialogs/dialog-office-bot/commit/82b2a189b31cfa0fbc4b1aea66ddf61ceca23262 I've moved all my work under `ConfluenceGroupManager` folder to avoid conflicts with @willy2dg's work.
No file changed from https://github.com/dialogs/dialog-office-bot/commit/7eb1f61393b376fca150db55ad47a00e30910970

**Comment by Drymonade** [comment]
@ShellAddicted I've checked your solution - all is ok. Merged.

**Pull request merged**
